spring:
  data:
    mongodb:
      auto-index-creation: true

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/forkfork

---
spring:
  config:
    activate:
      on-profile: ( beta | real )
  data:
    mongodb:
      uri: ${MONGO_URL}
