spring:
  application:
    name: forkfork
  profiles:
    include: mongodb, kakao, auth
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB

sharing:
  expiration-hours: 24

---
spring:
  config:
    activate:
      on-profile: real

logging:
  level:
    root: info
