jwt:
  access-expiration-time: 86400000 # 1 day
  refresh-expiration-time: 432000000 # 5 days
  refresh-cookie-time: 432000 # 5 days
  secret: ${JWT_SECRET}

s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket: ${S3_BUCKET}
