spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/forkfork

---
spring:
  config:
    activate:
      on-profile: beta
  data:
    mongodb:
      uri: ${MONGO_URL}
