on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          WEBHOOK_URL: ${{ secrets.BETA_WEBHOOK_URL }}
        run: |
          curl -X GET $WEBHOOK_URL
